### ISSUE TITLE
How to get the ArduCAM.h?

### ISSUE THREAD

**Issue by matsujirushi** [jimbobbennett/wio-terminal-arducam#1]
Hi,
I cannot found the ArduCAM.h in this repository.
Could you tell me how to get the ArduCAM.h?

https://github.com/jimbobbennett/wio-terminal-arducam/blob/main/src/arducam_ov2640_wio.h#L4

**Comment by jimbobbennett** [comment]
You need to add the ArduCAM Arduino library into the `lib` folder.

* Clone the [ArduCAM GitHub repo](https://github.com/ArduCAM/Arduino) repo
* Copy the ArduCAM folder from that repo into the `lib` folder

**Comment by matsujirushi** [comment]
Hi @jimbobbennett ,
Thank you!
